# Generated by Django 5.1.6 on 2025-05-12 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="isGlutenFree",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="isHalal",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="isVegan",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restaurants",
                to="restaurants.menu",
            ),
        ),
    ]
