# Generated by Django 5.1.6 on 2025-05-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_item_isglutenfree_item_ishalal_item_isvegan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_picture",
            field=models.CharField(
                blank=True, default="item_pictures/default.jpeg", null=True
            ),
        ),
    ]
