# Generated by Django 5.1.6 on 2025-05-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_alter_item_item_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="is_active",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="_is_active",
            field=models.BooleanField(db_column="is_active", default=False),
        ),
    ]
