# Generated by Django 5.1.6 on 2025-05-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_remove_restaurant_is_active_restaurant__is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="_is_active",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
